version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    container_name: lifein-frontend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: lifein-backend
    environment:
      - MONGO_URI=mongodb://db:27017/lifein
      - JWT_SECRET=your-super-secret-key-that-is-long-and-random
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    container_name: lifein-db
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: